<?php
// This is a random PHP script generated by LLaMA
// Feel free to use this in your own projects

function get_random_number($min, $max) {
  return rand($min, $max);
}

$random_number = get_random_number(1, 10);
echo "Random number: " . $random_number;
?>